### ISSUE TITLE
Bug: undefined_method size on github callback

### ISSUE THREAD

**Issue by vsmart** [rubycorns/rorganize.it#622]
When attempting to sign in with github....

```
Processing by OmniauthCallbacksController#github as HTML
  Parameters: {"code"=>"xxxxx", "state"=>"xxxxx"}
  Person Load (0.2ms)  SELECT  "people".* FROM "people" WHERE "people"."provider" = ? AND "people"."uid" = ? ORDER BY "people"."id" ASC LIMIT ?  [["provider", "github"], ["uid", "...."], ["LIMIT", 1]]
Completed 401 Unauthorized in 212ms (ActiveRecord: 0.2ms)



NoMethodError - undefined method `size' for nil:NilClass:
  app/models/person.rb:66:in `block in from_omniauth'
  app/models/person.rb:62:in `from_omniauth'
  app/controllers/omniauth_callbacks_controller.rb:5:in `github'
```

**Comment by vsmart** [comment]
jk 

> brew install imagemagick

DO NOT MISS THIS STEP!
